name: build
on:
  pull_request:
  push:
    branches: [ rolling ]
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_image: ['ros:iron-ros-base', 'ros:rolling-ros-base']
    container:
      image: ${{ matrix.docker_image }}
    timeout-minutes: 30
    steps:
    - name: Deps
      run: |
        apt update && apt install -y curl
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    - uses: actions/checkout@v2
    - name: rosdep
      run: |
        rosdep update
        rosdep install --from-paths . -yir
    - name: build
      run: /ros_entrypoint.sh colcon build
