name: Build rmw_zenoh

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ros:foxy

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Package dependencies
      run: |
        apt-get update && apt-get install -y \
          curl

    - name: Setup workspace
      run: |
        mkdir -p rmw_zenoh_ws/src
        cd rmw_zenoh_ws
        vcs import src < ../rmw_zenoh.repos
        rm -rf src/rmw_zenoh
        ln -s \
          ${PWD}/../rmw_zenoh_cpp/ \
          ${PWD}/../zenoh_vendor/ \
          ${PWD}/../zenoh_pico_vendor/ \
          src/

    - name: Setup rust nightly
      shell: bash
      run: |
        curl https://sh.rustup.rs -sSf > rustup.sh
        chmod +x rustup.sh
        ./rustup.sh \
          --default-toolchain nightly \
          --profile minimal \
          -y
        source ${HOME}/.cargo/env
        cargo install cbindgen

    - name: Package dependencies
      run: |
        cd rmw_zenoh_ws
        rosdep update
        DEBIAN_FRONTEND=noninteractive rosdep install \
          --default-yes \
          --from-paths src \
          --ignore-src \
          --rosdistro foxy

    - name: Build
      shell: bash
      run: |
        source ${HOME}/.cargo/env
        cd rmw_zenoh_ws
        source /opt/ros/foxy/setup.bash
        colcon build \
          --cmake-args \
            -DCMAKE_BUILD_TYPE=RELEASE
        source install/setup.bash
        colcon build \
          --cmake-args \
            -DCMAKE_BUILD_TYPE=RELEASE \
          --cmake-force-configure

    - name: Test
      shell: bash
      run: |
        cd rmw_zenoh_ws
        source /opt/ros/foxy/setup.bash
        source install/setup.bash         
        export RMW_IMPLEMENTATION=rmw_zenoh_cpp
        colcon test \
          --packages-select rmw_zenoh_cpp
        colcon test-result \
          --verbose
        colcon test-result \
          --all

    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: colcon-logs
        path: rmw_zenoh/log
