name: Build zenoh-pico_vendor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: ros:foxy

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Install missing dependencies
      run: |
        sudo apt update
        rosdep update
        DEBIAN_FRONTEND=noninteractive rosdep install \
          --default-yes \
          --from-paths zenoh_pico_vendor \
          --ignore-src \
          --rosdistro foxy

    - name: Build
      run: |
        . /opt/ros/foxy/setup.sh
        colcon build \
          --event-handlers console_cohesion+ \
          --packages-up-to zenoh_pico_vendor

    - name: Run tests
      run: |
        . /opt/ros/foxy/setup.sh
        colcon test \
          --return-code-on-test-failure \
          --event-handlers console_cohesion+ \
          --packages-up-to zenoh_pico_vendor
