name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: ros-tooling/setup-ros@0.0.25
        with:
          required-ros-distributions: foxy
      - name: Build and test
        uses: ros-tooling/action-ros-ci@0.0.19
        with:
          target-ros2-distro: foxy
          vcs-repo-file-url: https://raw.githubusercontent.com/osrf/rmw_zenoh/main/rmw_zenoh.repos
          package-name: rmw_zenoh_cpp
      - uses: actions/upload-artifact@v1
        with:
          name: colcon-logs
          path: ros_ws/log
