name: style
on:
  pull_request:
  push:
    branches: [ main ]
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_image: ['ros:iron-ros-base', 'ros:rolling-ros-base']
    container:
      image: ${{ matrix.docker_image }}
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: style
      run: /ros_entrypoint.sh ament_uncrustify rmw_zenoh_cpp/
